"""Add subcategory, color, country_of_origin to Product

Revision ID: be822510bdda
Revises: 
Create Date: 2025-05-23 23:36:59.955159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be822510bdda'
down_revision = '60e3649b727c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('subcategory', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('country_of_origin', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'country_of_origin')
    op.drop_column('products', 'color')
    op.drop_column('products', 'subcategory')
    # ### end Alembic commands ###
